<?php 

function subscribe_alter(array &$types) {
  $types['table']['#attached']['library'][] = 'subscribe/subscribe.lib';
}

function subscribe_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
    );
  switch ($key) {
    case 'subscribe_submit':
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = t('Subscribe Confirmation');
    $message['body'][] = "Hello " . $params['name'] . "!";
    $message['body'][] = t("You received this confirmation email for @email from our site. To confirmation subscription please goto to the following link.", array('@email'=>$params['email']));
    $message['body'][] = "Link: " . $params['link'];
    break;
  }
}
