<?php 
/**
 * @File
 * Subscribe module for Drupal 8.
 * @author Ahmed Raza
 */
function subscribe_element_info_alter(array &$types) {
  $types['table']['#attached']['library'][] = 'subscribe/subscribe.lib';
}

/**
 * @File
 * hook_mail for subscription mails.
 */
function subscribe_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
    );
  switch ($key) {
    case 'subscribe_submit':
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = t('Subscribe Confirmation');
    $message['body'][] = "Dear " . $params['name'] . "!";
    $message['body'][] = t("You received this confirmation email for @email from @site. To confirm subscription please goto to the following link.", array('@email'=>$params['email'], '@site'=>\Drupal::config('system.site')->get('name')));
    $message['body'][] = "Link: " . $params['link'];
    break;
    case 'subscribe_resend':
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = t('Resend Subscribe Confirmation');
    $message['body'][] = "Dear " . $params['name'] . "!";
    $message['body'][] = t("You received this confirmation email for @email from @site. To confirm subscription please goto to the following link.", array('@email'=>$params['email'], '@site'=>\Drupal::config('system.site')->get('name')));
    $message['body'][] = "Link: " . $params['link'];
    break;
    case 'subscribe_remove':
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = t('Unsubscribe');
    $message['body'][] = "Dear " . $params['name'] . "!";
    $message['body'][] = t("You received this confirmation email for @email from @site. To confirm subscription please goto to the following link.", array('@email'=>$params['email'], '@site'=>\Drupal::config('system.site')->get('name')));
    $message['body'][] = "Link: " . $params['link'];
    break;
  }
}
